config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "user_sessions#new"
  post "/login", to: "user_sessions#create"
  delete "/logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resources :posts do
    resources :comments
  end
  resources :bookmarks

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :send_bookmark_notification

  validates :user_id, uniqueness: { scope: :post_id }

  def send_bookmark_notification
    NotificationMailer.new_bookmark_notification(post.user, post).deliver_later
  end

  def self.ransackable_associations(auth_object = nil)
    [ "post", "user" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "user_id", "post_id" ]
  end

  def self.pagination_per_page
    10
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :send_comment_notification

  validates :content, presence: true

  def send_comment_notification
    NotificationMailer.new_comment_notification(post.user, post, self).deliver_later
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :bookmarks
  has_many :comments
  has_many :users, through: :bookmarks

  validates :title, presence: true
  validates :description, presence: true

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "description", "title", "user_id" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "user" ]
  end

  def self.pagination_per_page
    10
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password_confirmation

  has_many :posts
  has_many :comments
  has_many :bookmarks
  has_many :bookmarked_posts, through: :bookmarks, source: :post

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    [ "name" ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @search = current_user.bookmarks.ransack(params[:q])
    @page = (params[:page].to_i > 0) ? params[:page].to_i : 1
    @bookmarks = @search.result(distinct: true).includes(:post)
    @bookmarks = @bookmarks.offset((@page - 1) * Post.pagination_per_page).limit(Post.pagination_per_page)
    @total_posts = @bookmarks.count
    @previous_page = @page > 1 ? @page - 1 : nil
    @next_page = @total_posts > @page * Post.pagination_per_page ? @page + 1 : nil
  end
  def create
    bookmark = Bookmark.new(bookmark_params)
    post = bookmark.post
    if bookmark.save
      flash[:notice] = "いいねしました!"
      redirect_to post_path(post)
    else
      flash[:alert] = "すでにいいねされています！"
      redirect_to post_path(post)
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    if bookmark.delete
      flash[:notice] = "いいねを解除しました"
      redirect_to bookmarks_path
    else
      flash[:alert] = bookmark.errors.full_messages
      redirect_to bookmarks_path
    end
  end

  def bookmark_params
    params.require(:bookmark).permit(:user_id, :post_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params)
    comment.user = current_user
    if comment.save
      flash[:notice] = t("flash.comments.create.success")
      redirect_to post_path(post)
    else
      flash.now[:alert] = comment.errors.full_messages
      render "posts/show"
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = Comment.find(params[:id])
    if comment.delete
      flash[:notice] = t("flash.comments.destroy.success")
      redirect_to post_path(post)
    else
      flash.now[:alert] = comment.errors.full_messages
      render "post/show"
    end
  end

  def edit
    @comment = Comment.includes(:post, :user).find(params[:id])
    @post = @comment.post
  end

  def update
    comment = Comment.find(params[:id])
    post = comment.post
    if comment.update(comment_params)
      flash[:notice] = t("flash.comments.update.success")
      redirect_to post_path(post)
    else
      flash.now[:alert] = comment.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @page = (params[:page].to_i > 0) ? params[:page].to_i : 1
    @search = Post.ransack(params[:q])
    @posts = @search.result(distinct: true).includes(:user).offset((@page - 1)*(Post.pagination_per_page)).limit(Post.pagination_per_page)
    @total_posts = @search.result(distinct: true).includes(:user).count
    @previous_page = @page > 1 ? @page - 1 : nil
    @next_page = @total_posts > @page * (Post.pagination_per_page) ? @page + 1 : nil
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user = current_user
    if post.save
      flash[:notice] = t("flash.posts.create.success")
      redirect_to posts_path
    else
      flash.now[:alert] = post.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.includes(:user).find(params[:id])
    @comment = @post.comments.build
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      flash[:notice] = t("flash.posts.update.success")
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.delete
      flash[:notice] = t("flash.posts.destroy.success")
      redirect_to posts_path
    else
      flash.now[:alert] = post.errors.full_messages
      render :index, status: :unprocessable_entity
    end
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password])
    if user
      flash[:notice] = t("flash.user_sessions.create.success")
      redirect_to posts_path
    else
      flash.now[:alert] = t("flash.user_sessions.create.error")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:notice] = t("flash.user_sessions.destroy.logout")
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:notice] = t("flash.users.create.success")
      redirect_to login_path
    else
      flash.now[:alert] =  user.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/bookmarks/_bookmark.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h4 class="card-title"><%= link_to bookmark.post.title, post_path(bookmark.post.id), data: { turbo_frame: "_top" } %></h4><br>
    <p class="card-text"><%= simple_format(bookmark.post.description) %> </p>
      <p class="card-text text-end "><%= t('.user')%>:<%= bookmark.user.name %></p>
      <div class="d-flex justify-content-between">
        <%= form_with url: bookmark_path(bookmark), method: :delete, class: "d-inline", data: { turbo_frame: "_top" } do %>
          <button type="submit" class="btn btn-outline-danger">
            <i class="fa-solid fa-heart"></i> いいね解除
          </button>
        <% end %>
        <p class="card-text"><%= t('.post_day')%>:<%= bookmark.created_at.strftime('%Y年%m月%d日') %></p>
      </div>
  </div>
</div>

app/views/bookmarks/_search_form.html.erb
<%= search_form_for q, url: url do |form| %>
  <div class="row">
    <div class="col">
      <%= form.search_field :post_title_cont, class: "form-control", placeholder: "タイトル" %>
    </div>
    <div class="col">
      <%= form.search_field :post_description_cont, class: "form-control", placeholder: "本文" %>
    </div>
    <div class="col">
      <%= form.search_field :user_name_cont, class: "form-control", placeholder: "ユーザー名"%>
    </div>
    <div class="col-auto">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bookmarks/index.html.erb
<h3 class="text-center"><%= t('.title')%></h3>
<%= render 'search_form', q: @search, url: bookmarks_path %>
<% if @bookmarks.present?%>
  <turbo-frame>
    <%= render partial: 'bookmark', collection: @bookmarks %>
  </turbo-frame>
  <div class=" page container d-flex justify-content-center">
  <%= link_to 'Previous', bookmarks_path(page: @previous_page), data: { turbo_frame: "_top" }, class: "mx-2" if @previous_page %>
  <%= @page %>
  <%= link_to 'Next', bookmarks_path(page: @next_page), data: { turbo_frame: "_top" }, class: "mx-2" if @next_page %>
  </div>
<% else %>
  <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <strong><%= t('.bookmark_nil')%></strong>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container mt-5">  
  <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
    <h3 class="text-center"><%= t('.title')%></h3>
        <div class="card-body">
      <h4 class="card-title"><%= @post.title %></h4>
      <div class="mb-3">
        <p>by <%= @post.user.name %> <%= @post.created_at.strftime('%Y年%m月%d日') %></p>
      </div>
      <div class="card bg-light p-3 mb-3">
        <p class="card-text"><%= simple_format(@post.description) %></p>
      </div>
    </div>
  </div>
</div>
<div class="container mt-2">  
  <div class="mx-auto" style="max-width: 500px;">
    <strong><%= t('.comment_title')%></strong>
    <div class="card-body">
      <%= form_with(model: [@post, @comment], class: "needs-calidation") do |form| %>
        <div class="mb-3">
          <%= form.text_area :content, class: "form-control" %>
        </div>
        <div class="mb-3 text-end">
          <%= form.submit t('.submit'), class: "btn btn-primary"%>
        </div>
      <% end%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sns App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= javascript_include_tag "https://unpkg.com/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js", crossorigin: "anonymous", defer: true %>
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
        <ul class='navbar-nav align-items-center'>
          <% if logged_in? %>
            <li class="navbar_user"><strong>@</strong><%= current_user.name %></li>
          <% end %>
        </ul>
        <div class="container">
          <ul class='navbar-nav ms-auto align-items-center'>
            <li class='nav-item dropdown'>
              <% if logged_in? %>
                <%= link_to t('.logout'), logout_path, data: { turbo_method: :delete } %>
                <%= link_to t('.posts'), posts_path %>
                <%= link_to t('.post'), new_post_path %>
                <%= link_to t('.bookmark'), bookmarks_path %>
              <% else %>
                <%= link_to t('.login'), login_path %>
                <%= link_to t('.new_user'), new_user_path %>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <% flash.each do |key, messages| %>
      <div class="alert <%= key == "notice" ? "alert-success" : "alert-danger" %>">
        <% if messages.is_a?(Array) %>
          <% messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% else %>
          <%= messages %>  
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card mb-3">
  <div class="card-body">
    <h4 class="card-title"><%= link_to post.title, post_path(post), data: { turbo_frame: "_top" } %></h4><br>
    <p class="card-text"><%= simple_format(post.description) %> </p>
    <p class="card-text text-end "><%= t('.user')%>:<%= post.user.name %>
    <p class="card-text text-end "><%= t('.post_day')%>:<%= post.created_at.strftime('%Y年%m月%d日') %></p>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for q, url: url do |form| %>
  <div class="row">
    <div class="col">
      <%= form.search_field :title_cont, class: "form-control", placeholder: "タイトル" %>
    </div>
    <div class="col">
      <%= form.search_field :description_cont, class: "form-control", placeholder: "本文" %>
    </div>
    <div class="col">
      <%= form.search_field :user_name_cont, class: "form-control", placeholder: "ユーザー名"%>
    </div>
    <div class="col-auto">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-5">  
  <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
    <h3 class="text-center"><%= t('.title')%></h3>
    <div class="card-body">
      <%= form_with(model: @post, class: "needs-calidation") do |form| %>
        <div class="mb-3">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control", rows:"5" %>
        </div>
        <div class="row justify-content-between">
          <div class="col-auto">
            <%= form.submit t('.update'), class:"btn btn-primary" %>
          </div>
          <div class="col-auto text-end">
            <%= link_to t('.back'), post_path(@post)%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1 class="text-center"><%= t('.title')%></h1>
<div class="container mb-3">
  <div class="row">
    <%= render 'search_form', q: @search, url: posts_path %>
  </div>
</div>
<% if @posts.exists? %>
  <turbo-frame>
    <%= render @posts %>
  </turbo-frame>
  <div class=" page container d-flex justify-content-center">
  <%= link_to 'Previous', posts_path(page: @previous_page), data: { turbo_frame: "_top" }, class: "mx-2" if @previous_page %>
  <%= @page %>
  <%= link_to 'Next', posts_path(page: @next_page), data: { turbo_frame: "_top" }, class: "mx-2" if @next_page %>
</div>
<% else %>
  <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <strong>検索結果はありません</strong>
  <div>
<% end %>

app/views/posts/new.html.erb
<div class="container mt-5">  
  <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
    <h3 class="text-center"><%= t('.title')%></h3>
    <div class="card-body">
      <%= form_with(model: @post, class: "needs-calidation") do |form| %>
        <div class="mb-3">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control", rows:"5" %>
        </div>
        <%= form.submit t('.register') %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5">  
  <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
    <h3 class="text-center"><%= t('.title')%></h3>
        <div class="card-body">
      <h4 class="card-title"><%= @post.title %></h4>
      <div class="mb-3">
        <p>by <%= @post.user.name %> <%= @post.created_at.strftime('%Y年%m月%d日') %></p>
      </div>
      <div class="card bg-light p-3 mb-3">
        <p class="card-text"><%= simple_format(@post.description) %></p>
      </div>
        <% if @post.user.id == current_user.id%>
          <div class="row justify-content-center ">
            <div class="col-auto">
              <%= link_to t('.edit'), edit_post_path(@post), class:"btn btn-primary" %>
            </div>
            <div class="col-auto">
              <%= button_to t('.delete'), post_path(@post), method: :delete, class: "btn btn-danger" %>
            </div>
            <div class="col-auto">
              <%= form_with url: bookmarks_path(@post), method: :post, class: "d-inline" do %>
                <%= hidden_field_tag "bookmark[post_id]", @post.id %>
                <%= hidden_field_tag "bookmark[user_id]", current_user.id%>
                <button type="submit" class="btn btn-outline-danger">
                  <i class="fa-solid fa-heart"></i> いいね
                </button>
              <% end %>
            </div>
          </div>
        <% end%>
    </div>
  </div>
</div>
<div class="container mt-2">  
  <div class="mx-auto" style="max-width: 500px;">
    <div class="card-body">
      <%= form_with(model: [@post, @comment], class: "needs-calidation") do |form| %>
        <div class="mb-3">
          <%= form.label :content, class: "form-label" %>
          <%= form.text_area :content, class: "form-control" %>
        </div>
        <div class="mb-3 text-end">
          <%= form.submit t('.submit'), class: "btn btn-primary"%>
        </div>
      <% end%>
    </div>
  </div>
</div>
<div class="container mt-2">  
  <div class="mx-auto" style="max-width: 500px;">
    <div class="card-body">
      <% if @comments.exists? %>
        <h3><%= t('.comment')%></h3>
        <div class="card-body">
            <% @comments.each do |comment| %>
              <div class="comment">
                <div>
                  <p><strong><%= comment.user.name %></strong></p>
                  <p><%= comment.content %></p>
                </div>
                <% if comment.user.id == current_user.id %>
                  <div class="row justify-content-end ">
                    <div class="col-auto">
                      <%= link_to t('.edit'), edit_post_comment_path(@post, comment) %>
                    </div>
                    <div class="col-auto">
                      <%= link_to t('.delete'), post_comment_path(@post, comment), data:{ turbo_method: :delete } %>
                    </div>
                  </div>
                <% end%>
              </div>
            <% end %>
        </div>
      <% else %>
        <strong><%= t('.comment_nil') %></strong>
      <% end %>
    </div>
  </div>
</div>

   

app/views/user_sessions/new.html.erb
<div class="container mt-5">  
  <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
    <h3><%= t('.title') %></h3>
    <div class="card-body">
      <%= form_with url: login_path, class: "needs-validation" do |form| %>
        <div class="mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :password, class: "form-label" %>
          <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.submit t('.login') %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container mt-5">  
  <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
    <h3>新規登録</h3>
    <div class="card-body">
      <%= form_with(model: @user, class: "needs-validation") do |form| %>
        <div class="mb-3">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class:"form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :password, class: "form-label" %>
          <%= form.password_field :password, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.label :password_confirmation, class: "form-label" %>
          <%= form.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= form.submit "登録" %>
        </div>
      <% end %>
    </div>
  </div>
</div>